CREATE TABLE `guestInquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`adultsCount` int NOT NULL DEFAULT 2,
	`childrenCount` int NOT NULL DEFAULT 0,
	`infantsCount` int NOT NULL DEFAULT 0,
	`preferredArea` varchar(255),
	`preferredDateFrom` varchar(20),
	`preferredDateTo` varchar(20),
	`originCountry` varchar(100),
	`languages` varchar(500),
	`dietaryRestrictions` text,
	`specialRequests` text,
	`assignedHostId` int,
	`assignedExperienceId` int,
	`assignedBookingId` int,
	`assignedStaffName` varchar(255),
	`staffNotes` text,
	`paymentLinkUrl` text,
	`paymentLinkSentAt` timestamp,
	`status` enum('submitted','reviewing','host_contacted','confirmed','payment_sent','payment_received','completed','rejected','cancelled') NOT NULL DEFAULT 'submitted',
	`rejectionReason` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`hostContactedAt` timestamp,
	`confirmedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `guestInquiries_id` PRIMARY KEY(`id`)
);
